[package]
name = "hc"
version = "0.0.2"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[dependencies]
holochain_net = { path = "../net" }
holochain_core_types = { path = "../core_types" }
holochain_core = { path = "../core" }
holochain_cas_implementations = { path = "../cas_implementations" }
holochain_container_api = { path = "../container_api" }
holochain_wasm_utils = { path = "../wasm_utils" }
structopt = "0.2"
failure = "^0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.4"
semver = { version = "0.9.0", features = ["serde"] }
uuid = { version = "^0.6", features = ["v4", "serde"] }
assert_cmd = "0.9.0"
tempfile = "3"
base64 = "0.9"
dir-diff = "0.3.1"
colored = "1.6"
ignore = "0.4.3"
rustyline = "^2.1"
